const card = (title, copy, icon = 'signal', value = '', tone = 'blue', cue = '') => ({ title, copy, icon, value, tone, cue })

export const layeredSceneCatalog = {
  '06': {
    title: 'WHAT IS BEMA HUB?', subtitle: 'A creative economy platform built on mutual exchange.', layout: 'cards',
    items: [
      card('Professional Creators', 'Bring original creative value, experiences, and ideas to Bema Hub.', 'user', '', 'blue', 'highlight-creators'),
      card('Participation Assets', 'Access creative value through LoopCode, Loop Activity, and VIP experiences.', 'play', '', 'cyan', 'highlight-assets'),
      card('Builders Help Value Move', 'Builders extend reach with LoopLink and LoopLock through the community.', 'people', '', 'purple', 'highlight-builders'),
    ],
    callout: 'Creators bring real value. Builders help it reach more people.',
    footer: [['signal', 'What is Bema Hub'], ['music', 'Creative value in motion'], ['people', 'Community of Rewarded Engagement']],
  },
  '07': {
    title: 'WHAT IS BEMA CORE?', subtitle: 'Community of Rewarded Engagement.', layout: 'cards',
    items: [
      card('Mutual Exchange', 'Participants access real creative value.', 'refresh', '', 'cyan', 'pillar-exchange'),
      card('Builders in Action', 'Builders help that value reach more people.', 'people', '', 'blue', 'pillar-builders'),
      card('Sustainable Creative Economy', 'Creators gain a stronger path to keep creating.', 'chart', '', 'purple', 'pillar-economy'),
    ],
    callout: 'Clear value. Meaningful participation. Real movement.',
    footer: [['heart', 'Mutual Exchange'], ['people', 'Builders in Action'], ['music', 'Creative value in motion']],
  },
  '09': {
    title: 'PROGRAMS OVERVIEW', subtitle: 'Explore the core experiences inside Bema Hub.', layout: 'cards', columns: 2,
    items: [
      card('Campaigns', 'Participate in creator-led experiences.', 'megaphone', '', 'blue', 'program-campaigns'),
      card('Events', 'Join live moments and community gatherings.', 'calendar', '', 'purple', 'program-events'),
      card('Changemakers', 'Discover people making meaningful impact.', 'people', '', 'purple', 'program-changemakers'),
      card('Creator Stories', 'See real progress and proof updates.', 'play', '', 'purple', 'program-stories'),
    ],
    footer: [['chart', 'Campaigns'], ['signal', 'Events'], ['people', 'Changemakers'], ['music', 'Creator Stories']],
  },
  '10': {
    title: 'PARTICIPATION JOURNEY', subtitle: 'How a Builder moves through the experience.', layout: 'flow',
    items: [
      card('Choose Access Level', 'Select the campaign experience that fits.', 'crown', '01', 'blue', 'journey-1'),
      card('Receive Participation Assets', 'Unlock creator value and experiences.', 'gift', '02', 'blue', 'journey-2'),
      card('Activate LoopLink or LoopCode', 'Use your personal participation tools.', 'link', '03', 'blue', 'journey-3'),
      card('Another Person Participates', 'A confirmed participation creates a LoopLock.', 'people', '04', 'cyan', 'journey-4'),
      card('Loop Activity Grows', 'Your verified movement becomes visible.', 'chart', '05', 'blue', 'journey-5'),
    ],
    callout: 'Each confirmed participation through your LoopLink or LoopCode becomes a LoopLock.',
    footer: [['people', 'Choose Access Level'], ['signal', 'LoopLink'], ['chart', 'Loop Activity']],
  },
  '11': {
    title: 'ECHOLOOP EXPLAINED', subtitle: 'Four connected tools that make participation visible.', layout: 'flow',
    items: [
      card('LoopLink', 'Your personal sharing link.', 'link', '01', 'blue', 'term-looplink'),
      card('LoopCode', 'Your personal share code.', 'qr', '02', 'cyan', 'term-loopcode'),
      card('LoopLock', 'A confirmed participation through your tools.', 'lock', '03', 'purple', 'term-looplock'),
      card('Loop Activity', 'Where movement and impact are tracked.', 'chart', '04', 'blue', 'term-activity'),
    ],
    callout: 'Qualifying LoopLocks may contribute to Recognized Impact according to campaign rules.',
    footer: [['signal', 'LoopLink'], ['qr', 'LoopCode'], ['lock', 'LoopLock'], ['chart', 'Loop Activity']],
  },
  '12': {
    title: 'ACCESS LEVELS', subtitle: 'The vertical climb within the campaign.', layout: 'stack',
    items: [
      card('Participation Level', 'Entry point into the campaign experience.', 'user', '01', 'cyan', 'level-participation'),
      card('VIP Access', 'Deeper creator assets and a more connected experience.', 'star', '02', 'purple', 'level-vip'),
      card('Signature VIP', 'Deepest access, exclusive assets, and identity-based participation.', 'crown', '03', 'amber', 'level-signature'),
    ],
    callout: 'Access Levels determine what you receive, not your Recognized Impact rate.',
    footer: [['people', 'Participation Level'], ['heart', 'VIP Access'], ['lock', 'Signature VIP']],
  },
  '13': {
    title: 'COMMUNITY BUILDER TIERS', subtitle: 'The horizontal spread of Loop Activity.', layout: 'flow', compact: true,
    items: [
      card('Builder', 'First active step.', 'user', '01', 'cyan', 'tier-builder'),
      card('Advocate', 'Intentional sharing and trust.', 'people', '02', 'blue', 'tier-advocate'),
      card('Champion', 'Stronger campaign movement.', 'trophy', '03', 'purple', 'tier-champion'),
      card('Partner', 'Meaningful reach and deeper alignment.', 'handshake', '04', 'blue', 'tier-partner'),
      card('Partner Elite', 'Highest Community Builder Tier.', 'crown', '05', 'amber', 'tier-elite'),
    ],
    callout: 'Community Builder Tiers are earned through Loop Activity and qualifying LoopLocks. They are not purchased.',
    footer: [['people', 'Community Builder Tiers'], ['chart', 'Loop Activity'], ['lock', 'Qualifying LoopLocks']],
  },
  '15': {
    title: 'LOOP ACTIVITY & RECOGNIZED IMPACT', subtitle: 'Clear status. Verified movement. Transparent results.', layout: 'status', compact: true,
    items: [
      card('Pending LoopLock', 'Loop activity submitted and awaiting review.', 'clock', 'PENDING', 'amber', 'status-pending'),
      card('Confirmed LoopLock', 'Loop activity verified and confirmed as valid.', 'shield', 'VERIFIED', 'blue', 'status-confirmed'),
      card('Qualified LoopLock', 'LoopLock meets campaign criteria and is eligible.', 'star', 'QUALIFIED', 'cyan', 'status-qualified'),
      card('Recognized Impact Pending', 'Qualified activity is under impact review.', 'chart', 'IN REVIEW', 'purple', 'status-impact-pending'),
      card('Recognized Impact Confirmed', 'Impact verified and confirmed per campaign rules.', 'check', 'CONFIRMED', 'blue', 'status-impact-confirmed'),
      card('Recognized Impact Released', 'Recognized Impact recorded and reflected in totals.', 'megaphone', 'RELEASED', 'cyan', 'status-released'),
    ],
    callout: 'Qualified LoopLocks may contribute to Recognized Impact according to campaign rules.',
    footer: [['chart', 'Loop Activity'], ['heart', 'Recognized Impact'], ['lock', 'Qualified LoopLocks']],
  },
  '16': {
    title: 'HOME DASHBOARD', subtitle: 'Welcome back. Here’s what is happening on Bema Hub today.', layout: 'dashboard',
    items: [
      card('Active Campaigns', 'See what is live.', 'chart', '39', 'blue', 'dashboard-today'),
      card('Changemakers', 'View community movement.', 'people', '18', 'cyan', 'dashboard-today'),
      card('Engagement', 'Track ecosystem activity.', 'signal', '12.6K', 'purple', 'dashboard-today'),
      card('Upcoming Events', 'Open Enrollment Kickoff · Creator Community Q&A', 'heart', '3 LIVE', 'blue', 'dashboard-events'),
      card('Featured Campaigns', 'Music for Change · Creativity for Good · Community Builders', 'music', 'VIEW ALL', 'cyan', 'dashboard-campaigns'),
    ],
    footer: [['chart', 'Home Dashboard'], ['signal', 'Active Campaigns'], ['heart', 'Upcoming Events'], ['music', 'Featured Campaigns']],
  },
  '17': {
    title: 'CAMPAIGNS PAGE WALKTHROUGH', subtitle: 'Discover creator-led campaigns.', layout: 'dashboard',
    items: [
      card('Sound of Tomorrow', 'by NovaWave · Participation Level', 'music', 'FEATURED', 'blue', 'campaign-featured'),
      card('Stage to Spotlight', 'by Echo Collective', 'chart', 'LIVE', 'cyan', 'campaign-grid'),
      card('Move the Culture', 'by Flow Studio', 'people', 'TRENDING', 'purple', 'campaign-grid'),
      card('Loop Activity', '218 Builders joined Stage to Spotlight', 'signal', 'REAL TIME', 'blue', 'campaign-activity'),
      card('Explore Campaigns', 'Find a campaign that moves you.', 'heart', 'START', 'cyan', 'campaign-cta'),
    ],
    footer: [['chart', 'Campaigns Page'], ['people', 'Participation Level'], ['heart', 'Featured Campaigns'], ['signal', 'Loop Activity']],
  },
  '18': {
    title: 'CAMPAIGN DETAIL PAGE', subtitle: 'Real creative value. Clear mutual exchange.', layout: 'dashboard',
    items: [
      card('New Single Launch: Echoes', 'Jaylen Vibes · Music Creator · Atlanta, GA', 'music', 'CREATOR', 'blue', 'detail-purpose'),
      card('Campaign Purpose', 'Support the launch of “Echoes” and amplify real music to real listeners.', 'heart', 'WHY', 'cyan', 'detail-purpose'),
      card('Participation Assets', 'Early preview · Behind the scenes · Artwork · VIP listening session', 'signal', '5 ASSETS', 'purple', 'detail-assets'),
      card('Access Levels', 'Participation Level · VIP Access · Signature VIP', 'lock', '3 LEVELS', 'blue', 'detail-levels'),
      card('Creator Proof & Updates', 'Verified creator · Previous campaigns delivered · Regular updates', 'chart', '100%', 'cyan', 'detail-proof'),
    ],
    footer: [['heart', 'Campaign Detail'], ['music', 'Creative Value'], ['signal', 'Participation Assets'], ['lock', 'Access Levels']],
  },
  '19': {
    title: 'CHOOSING YOUR ACCESS LEVEL', subtitle: 'Find the path that fits your campaign experience.', layout: 'cards',
    items: [
      card('Participation Level', 'Core campaign value and essential participation assets.', 'people', 'START', 'cyan', 'level-participation'),
      card('VIP Access', 'Deeper creator experiences and exclusive assets.', 'heart', 'GO DEEPER', 'blue', 'level-vip'),
      card('Signature VIP', 'Deepest access and identity-based participation.', 'lock', 'ELEVATE', 'purple', 'level-signature'),
    ],
    footer: [['people', 'Choose Access Level'], ['people', 'Participation Level'], ['heart', 'VIP Access'], ['lock', 'Signature VIP']],
  },
  '20': {
    title: 'PARTICIPATION ASSETS DELIVERED', subtitle: 'What you receive inside the campaign experience.', layout: 'list', darkPanel: true,
    items: [
      card('Music Access', 'Exclusive tracks, stems, and behind-the-scenes audio.', 'music', '✓', 'blue', 'asset-music'),
      card('Exclusive Content', 'Unreleased videos, early drops, and creator stories.', 'video', '✓', 'purple', 'asset-content'),
      card('Creator Updates', 'Direct updates and announcements from the creator.', 'people', '✓', 'cyan', 'asset-updates'),
      card('Event Access', 'Live sessions, AMAs, rehearsals, and special events.', 'signal', '✓', 'purple', 'asset-events'),
      card('Community Experience', 'Connect, collaborate, and grow with fellow supporters.', 'people', '✓', 'cyan', 'asset-community'),
    ],
    callout: 'You participate. You unlock. You get real creative value.',
    footer: [['people', 'Participation Assets'], ['music', 'Music Access'], ['video', 'Exclusive Content'], ['people', 'Creator Updates']],
  },
  '21': {
    title: 'LOOPLINK & LOOPCODE ACTIVATION', subtitle: 'Your personal participation tools.', layout: 'tools',
    items: [
      card('LoopLink', 'https://bemahub.com/join/joyceroot', 'signal', 'COPY · SHARE', 'blue', 'copy-link'),
      card('LoopCode', 'JOYCE-7249', 'qr', 'PERSONAL CODE', 'purple', 'reveal-code'),
      card('Live Loop Activity', 'Alex joined via LoopLink · Taylor joined via LoopCode · Jamie joined via LoopLink', 'people', '12 JOINED', 'cyan', 'activity-update'),
    ],
    callout: 'When someone joins using your LoopLink or LoopCode, they are connected to your Loop Activity.',
    footer: [['signal', 'LoopLink'], ['qr', 'LoopCode'], ['heart', 'Share Responsibly'], ['chart', 'Loop Activity']],
  },
  '22': {
    title: 'LOOPLOCK CONFIRMATION', subtitle: 'How a confirmed participation is created.', layout: 'flow',
    items: [
      card('Share LoopLink or LoopCode', 'You share your personal participation tool.', 'signal', '01', 'blue', 'flow-1'),
      card('Another Person Participates', 'They click your link or enter your code.', 'people', '02', 'cyan', 'flow-2'),
      card('LoopLock Confirmed', 'Participation is verified and a LoopLock is created.', 'lock', '03', 'purple', 'flow-3'),
      card('Loop Activity Updates', 'The new LoopLock appears in real time.', 'chart', '04', 'blue', 'flow-4'),
    ],
    callout: 'A LoopLock means another person’s participation is confirmed through your LoopLink or LoopCode.',
    footer: [['lock', 'LoopLock Confirmation'], ['people', 'Participation Flow'], ['chart', 'Loop Activity']],
  },
  '23': {
    title: 'QUALIFIED LOOPLOCKS', subtitle: 'Campaign rules and verification matter.', layout: 'status',
    items: [
      card('Pending LoopLock', 'Activity submitted and awaiting review.', 'signal', 'UNDER REVIEW', 'amber', 'status-pending'),
      card('Confirmed LoopLock', 'Activity verified and confirmed as valid.', 'lock', 'VERIFIED', 'blue', 'status-confirmed'),
      card('Qualified LoopLock', 'Meets campaign rules and may contribute to Recognized Impact.', 'heart', 'MAY CONTRIBUTE', 'cyan', 'status-qualified'),
      card('Not Qualified', 'Does not meet rules or is outside the eligible window.', 'signal', 'DOES NOT CONTRIBUTE', 'purple', 'status-not-qualified'),
    ],
    callout: 'Only Qualified LoopLocks may contribute to Recognized Impact according to campaign rules.',
    footer: [['lock', 'Qualified LoopLocks'], ['signal', 'Verification'], ['chart', 'Campaign Rules']],
  },
  '24': {
    title: 'RECOGNIZED IMPACT EXPLAINED', subtitle: 'Acknowledging real value created through verified movement.', layout: 'stack',
    items: [
      card('Acknowledges Real Value', 'Recognized Impact acknowledges value created through verified Loop Activity.', 'heart', '01', 'cyan', 'point-value'),
      card('Based on Qualifying LoopLocks', 'It is based on LoopLocks that meet campaign rules and eligibility criteria.', 'lock', '02', 'blue', 'point-qualified'),
      card('Verified and Released', 'Verification and release processes maintain integrity and transparency.', 'chart', '03', 'purple', 'point-verified'),
    ],
    footer: [['heart', 'Recognized Impact'], ['signal', 'Verification'], ['lock', 'Qualifying LoopLocks']],
  },
  '25': {
    title: 'TRUST & TRANSPARENCY', subtitle: 'Clear rules. Verified movement. Open communication.', layout: 'cards', columns: 2,
    items: [
      card('Clear Campaign Rules', 'Rules are simple, fair, and always visible.', 'chart', '', 'blue', 'trust-rules'),
      card('Verification Windows', 'Activities are verified during posted windows.', 'signal', '', 'cyan', 'trust-windows'),
      card('Creator Proof & Updates', 'Delivery progress and evidence remain visible.', 'people', '', 'purple', 'trust-proof'),
      card('Visible Status', 'Pending, confirmed, qualified, and released states are clear.', 'lock', '', 'blue', 'trust-status'),
    ],
    callout: 'Trust grows when rules, proof, and status remain visible.',
    footer: [['lock', 'Trust & Transparency'], ['chart', 'Campaign Rules'], ['signal', 'Verification'], ['people', 'Creator Proof']],
  },
  '26': {
    title: 'EVENTS PAGE WALKTHROUGH', subtitle: 'Discover live moments and community gatherings.', layout: 'dashboard',
    items: [
      card('Creative Futures Summit', 'May 28 · Bema Hub Virtual Stage', 'signal', 'FEATURED', 'blue', 'event-featured'),
      card('Creator Community Q&A', 'Live questions and practical answers.', 'people', 'LIVE', 'cyan', 'event-upcoming'),
      card('Loop Activity Masterclass', 'Practical tools for Builders.', 'chart', 'UPCOMING', 'purple', 'event-upcoming'),
      card('Event Categories', 'Workshops · Panels · Community · Music', 'heart', 'EXPLORE', 'blue', 'event-categories'),
      card('View Calendar', 'Save events and join from anywhere.', 'signal', 'OPEN', 'cyan', 'event-categories'),
    ],
    footer: [['signal', 'Events Page'], ['heart', 'Featured Events'], ['people', 'Live Community'], ['chart', 'View Calendar']],
  },
  '27': {
    title: 'EVENT DETAIL PAGE', subtitle: 'Join the moment.', layout: 'dashboard', qr: true,
    items: [
      card('Creative Futures Summit 2026', 'Inspire. Create. Impact.', 'signal', 'MAY 28', 'blue', 'event-hero'),
      card('Schedule', 'Opening Keynote · Builders in Action · From Idea to Impact', 'chart', '10:00–3:30', 'cyan', 'event-schedule'),
      card('What Attendees Get', 'Expert sessions · Resources · Networking · Recording access', 'heart', '4 BENEFITS', 'purple', 'event-benefits'),
      card('Register or Join', 'Free and open to all.', 'people', '128 REGISTERED', 'blue', 'event-cta'),
    ],
    footer: [['signal', 'Event Detail'], ['chart', 'Schedule'], ['heart', 'Attendee Benefits'], ['people', 'Register or Join']],
  },
  '28': {
    title: 'CHANGEMAKERS OVERVIEW', subtitle: 'Spotlight people creating meaningful movement.', layout: 'profiles', compact: true,
    items: [
      card('Amina Diallo', 'Youth Mentor & Creative Educator', 'people', '1.2K', 'cyan', 'changemaker-1'),
      card('Marcus Reed', 'Impact Strategist & Movement Leader', 'chart', '1.1K', 'blue', 'changemaker-2'),
      card('Jordan Miles', 'Community Builder & Social Entrepreneur', 'heart', '980', 'purple', 'changemaker-3'),
      card('Sophia Lee', 'Climate Advocate & Sustainability Leader', 'signal', '870', 'cyan', 'changemaker-4'),
      card('Tierra Vaughn', 'Creative Director & Visual Storyteller', 'music', '1.6K', 'purple', 'changemaker-5'),
      card('Darnell Brooks', 'UX Designer & Tech for Good Advocate', 'people', '1.3K', 'blue', 'changemaker-6'),
    ],
    footer: [['people', 'Changemakers'], ['heart', 'Meaningful Impact'], ['signal', 'Real Stories']],
  },
  '29': {
    title: 'CREATOR STORIES & PROOF UPDATES', subtitle: 'Real updates. Real delivery. Real creative value.', layout: 'dashboard',
    items: [
      card('Recent Creator Stories', 'Maya wrapped the brand anthem · Tariq is finalizing edits · Aisha delivers social assets today', 'people', '3 NEW', 'blue', 'story-1'),
      card('Recent Proof Updates', 'Campaign video draft · Social post set · Motion graphics preview', 'signal', 'LIVE', 'cyan', 'proof-update'),
      card('Delivery Status', 'Campaign Video 100% · Social Assets 85% · Influencer Clips 60%', 'chart', 'ON TRACK', 'purple', 'delivery-status'),
      card('Creator Spotlight', 'Jamal K. · Video Producer', 'music', '38 CREATORS', 'blue', 'creator-spotlight'),
      card('Progress Highlights', '92% of deliverables are on track.', 'heart', '92%', 'cyan', 'delivery-status'),
    ],
    footer: [['people', 'Creator Stories'], ['signal', 'Proof Updates'], ['chart', 'Real Delivery'], ['heart', 'Mutual Exchange']],
  },
  '30': {
    title: 'MY IMPACT DASHBOARD', subtitle: 'Track your Loop Activity, LoopLocks, and Recognized Impact.', layout: 'dashboard',
    items: [
      card('Total Loop Activity', '+342 this week', 'chart', '2,486', 'blue', 'metric-activity'),
      card('Pending LoopLocks', 'Awaiting verification', 'signal', '18', 'amber', 'metric-pending'),
      card('Qualified LoopLocks', 'Verified and qualified', 'lock', '127', 'cyan', 'metric-qualified'),
      card('Recognized Impact Status', 'You are building meaningful impact. Keep going!', 'heart', 'ON TRACK', 'purple', 'metric-impact'),
      card('Builder Tier Progress', 'Silver Builder · 2,460 / 5,000 points', 'people', '49%', 'blue', 'metric-tier'),
    ],
    footer: [['chart', 'My Impact'], ['chart', 'Loop Activity'], ['lock', 'Qualified LoopLocks'], ['people', 'Builder Progress']],
  },
  '31': {
    title: 'BUILDER PROGRESS TRACKER', subtitle: 'See your path across Community Builder Tiers.', layout: 'progress',
    items: [
      card('Builder', '1 LoopLock completed', 'people', '0%', 'cyan', 'current-tier'),
      card('Advocate', '3 LoopLocks completed', 'signal', '25%', 'blue', 'advance-progress'),
      card('Champion', '7 LoopLocks completed', 'chart', '50%', 'purple', 'advance-progress'),
      card('Partner', '15 LoopLocks in progress', 'heart', '75%', 'blue', 'current-tier'),
      card('Partner Elite', '30 LoopLocks next target', 'lock', '100%', 'purple', 'next-target'),
    ],
    callout: 'Next target: 15 LoopLocks to reach Partner.',
    footer: [['people', 'Builder Progress'], ['chart', 'LoopLock Milestones'], ['lock', 'Next Target']],
  },
  '32': {
    title: 'TOP REFERRERS & COMMUNITY MOMENTUM', subtitle: 'Visible movement helps value travel farther.', layout: 'leaderboard',
    items: [
      card('Creative_Jay', 'Community Builder', 'people', '128', 'cyan', 'rank-1'),
      card('DesignFlow', 'Visual Storyteller', 'chart', '97', 'blue', 'rank-2'),
      card('MelodyMinds', 'Music Creator', 'music', '86', 'purple', 'rank-3'),
      card('LoopQueen', 'Engagement Leader', 'heart', '72', 'blue', 'activity-update'),
      card('Visionary_Vee', 'Impact Connector', 'signal', '61', 'cyan', 'activity-update'),
      card('Weekly Momentum', '1,248 referrals · 2,976 LoopLinks · 4,532 community actions', 'chart', '+24%', 'purple', 'activity-update'),
    ],
    footer: [['people', 'Top Referrers'], ['signal', 'Loop Activity'], ['chart', 'Weekly Movement']],
  },
  '33': {
    title: 'FREQUENTLY ASKED QUESTIONS', subtitle: 'Clear answers before you choose your next step.', layout: 'faq',
    items: [
      card('What are the Access Levels?', 'They determine what you receive, not your Recognized Impact rate.', 'people', '01', 'blue', 'faq-1'),
      card('What do I receive?', 'Each level unlocks creator assets, experiences, and opportunities.', 'heart', '02', 'cyan', 'faq-2'),
      card('What is LoopLink?', 'Your personal sharing link that connects activity and invites.', 'signal', '03', 'purple', 'faq-3'),
      card('What are Qualified LoopLocks?', 'Verified participation that meets campaign rules.', 'lock', '04', 'blue', 'faq-4'),
      card('How is Recognized Impact measured?', 'Through qualifying actions, history, and verified contributions.', 'chart', '05', 'cyan', 'faq-5'),
    ],
    footer: [['signal', 'FAQ'], ['heart', 'Clear Answers'], ['people', 'Participation Questions']],
  },
  '34': {
    title: 'FINAL ENROLLMENT CALL TO ACTION', subtitle: 'Choose your access level and join the movement today.', layout: 'cta', qr: true,
    items: [
      card('Participation Level', 'Entry point into the campaign experience.', 'people', 'JOIN NOW', 'cyan', 'level-participation'),
      card('VIP Access', 'Deeper creator assets and a connected experience.', 'heart', 'UPGRADE', 'blue', 'level-vip'),
      card('Signature VIP', 'Deepest access and exclusive assets.', 'lock', 'GO ALL IN', 'purple', 'level-signature'),
      card('Join as a Builder', 'Be part of the movement. Create value. Help more people.', 'people', 'JOIN', 'cyan', 'join-builder'),
    ],
    footer: [['signal', 'Final Enrollment'], ['qr', 'Scan to Join'], ['people', 'Choose Access Level'], ['heart', 'Join as a Builder']],
  },
  '35': {
    title: 'THANK YOU & NEXT STEPS', subtitle: 'Stay connected and keep moving with Bema Hub.', layout: 'cards', columns: 2,
    items: [
      card('Check Your Email', 'Access details and resources are waiting in your inbox.', 'signal', '01', 'blue', 'step-email'),
      card('Join the Chat', 'Stay in the conversation and keep the momentum going.', 'people', '02', 'cyan', 'step-chat'),
      card('Explore Your Dashboard', 'Log in, explore programs, and personalize your experience.', 'chart', '03', 'purple', 'step-dashboard'),
      card('Share Your LoopLink', 'Invite others and build something meaningful together.', 'heart', '04', 'blue', 'step-looplink'),
    ],
    callout: 'Together, we create. Together, we grow.',
    footer: [['heart', 'Thank You'], ['signal', 'Next Steps'], ['chart', 'Explore Your Dashboard'], ['people', 'Stay Connected']],
  },
  '36': {
    title: 'LIVE Q&A', subtitle: 'Your questions are welcome.', layout: 'faq', utility: true,
    items: [
      card('How do Access Levels work?', 'Choose the campaign experience and assets that fit you.', 'people', '?', 'blue', 'question-1'),
      card('What counts as a LoopLock?', 'A confirmed participation through LoopLink or LoopCode.', 'lock', '?', 'cyan', 'question-2'),
      card('Where do I see Loop Activity?', 'Track it from your personal impact dashboard.', 'chart', '?', 'purple', 'question-3'),
      card('How do I choose a campaign?', 'Explore clear value, assets, access levels, and creator proof.', 'heart', '?', 'blue', 'question-4'),
    ],
    footer: [['signal', 'Open Enrollment Is Live'], ['lock', 'Lock Access'], ['people', 'Link & Share'], ['heart', 'Earn Impact']],
  },
  '37': {
    title: 'ENROLLMENT PROGRESS', subtitle: 'Real-time movement as viewers take action.', layout: 'dashboard', utility: true, qr: true,
    items: [
      card('Scans', 'Viewers opening enrollment', 'qr', '248', 'blue', 'advance-counts'),
      card('LoopLinks Activated', 'Personal tools now active', 'signal', '119', 'cyan', 'advance-counts'),
      card('New Builders', 'Community growth today', 'people', '76', 'purple', 'advance-counts'),
      card('Questions Answered', 'Live support completed', 'heart', '32', 'blue', 'advance-counts'),
      card('Overall Progress', 'Enrollment movement in real time', 'chart', '68%', 'cyan', 'advance-progress'),
      card('Live Activity Feed', 'Amina joined · Samuel activated LoopLink · Joyce chose VIP', 'signal', 'JUST NOW', 'purple', 'activity-update'),
    ],
    footer: [['signal', 'You Are Watching Live'], ['people', 'Live Chat Active'], ['heart', 'Like & Share']],
  },
  '39': {
    title: 'THE LOOP CONTINUES.', subtitle: 'Keep creating. Keep connecting. Keep moving value forward.', layout: 'cta', utility: true, qr: true,
    items: [
      card('Visit Your Dashboard', 'Track your activity and continue your journey.', 'chart', 'OPEN', 'blue', 'dashboard-cta'),
      card('Share Your LoopLink', 'Help creative value reach more people.', 'signal', 'SHARE', 'purple', 'looplink-cta'),
      card('Join the Community Chat', 'Stay connected after the live session.', 'people', 'JOIN', 'cyan', 'community-cta'),
    ],
    callout: 'Thank you for joining Bema Hub Open Enrollment 2026.',
    footer: [['heart', 'Thank You for Being Part of the Loop'], ['signal', 'Create Connections'], ['music', 'Share Value'], ['people', 'Move Forward']],
  },
}
