const cue = (id, label) => ({ id, label })

const SCENE_DURATIONS_SECONDS = Object.freeze({
  '01': 600,
  '02': 120,
  '03': 60,
  '04': 30,
  '05': 180,
  '06': 120,
  '07': 120,
  '08': 90,
  '09': 120,
  '10': 150,
  '11': 150,
  '12': 120,
  '13': 150,
  '14': 180,
  '15': 150,
  '16': 180,
  '17': 180,
  '18': 180,
  '19': 150,
  '20': 120,
  '21': 150,
  '22': 120,
  '23': 120,
  '24': 150,
  '25': 120,
  '26': 150,
  '27': 150,
  '28': 180,
  '29': 180,
  '30': 150,
  '31': 120,
  '32': 120,
  '33': 180,
  '34': 180,
  '35': 120,
  '36': 300,
  '37': 300,
  '38': 300,
  '39': 120,
})

const scene = (id, title, entry, during, continuous, exit) => ({
  scene: id,
  title,
  durationSeconds: SCENE_DURATIONS_SECONDS[id],
  entryCue: cue('entry', entry),
  continuousEffects: continuous,
  duringCues: during.map(([cueId, label]) => cue(cueId, label)),
  exitCue: cue('exit', exit),
})

export const sceneControls = [
  scene('01', 'Live Stream Starting Soon Countdown', 'Fade In and Light Sweep', [['pulse-qr', 'Pulse QR Prompt']], ['Countdown', 'Card breathing', 'Ambient glow', 'Particle drift'], 'Crossfade to Welcome Visualizer'),
  scene('02', 'Welcome Music Visualizer', 'Raise Spectrum Bars', [], ['Waveform movement', 'Equalizer pulse', 'Presenter frame glow'], 'Lower Visualizer Intensity'),
  scene('03', 'Host Standby Camera', 'Camera Dissolve', [['reveal-lower-third', 'Reveal Host Lower Third']], ['Background screen motion'], 'Swipe to Opening Stinger'),
  scene('04', 'Grand Opening Stinger', 'Reveal 3D Logo', [['statement-1', 'Reveal Creator Statement'], ['statement-2', 'Reveal Builder Statement'], ['statement-3', 'Reveal Community Statement']], ['Light streaks', 'Particle drift'], 'Flash to Host Welcome'),
  scene('05', 'Host Welcome and Agenda', 'Slide In Agenda', Array.from({ length: 10 }, (_, i) => [`agenda-${i + 1}`, `Highlight Agenda Item ${i + 1}`]), ['Ambient equalizer'], 'Fade Agenda and CTA'),
  scene('06', 'What Is Bema Hub', 'Soft Dissolve', [['highlight-creators', 'Highlight Creators'], ['highlight-assets', 'Highlight Participation Assets'], ['highlight-builders', 'Highlight Builders']], ['Subtle wave motion'], 'Dissolve to Bema CORE'),
  scene('07', 'What Is Bema CORE', 'Fade Background and Presenter', [['pillar-exchange', 'Reveal Mutual Exchange'], ['pillar-builders', 'Reveal Builders in Action'], ['pillar-economy', 'Reveal Sustainable Economy']], ['Glow accents'], 'Dissolve to Access Levels'),
  scene('08', 'Impact Statistics Overview', 'Dashboard Fade Up', [['highlight-active-campaigns', 'Highlight Active Campaigns'], ['highlight-changemakers', 'Highlight Changemakers'], ['highlight-builders', 'Highlight Builders Active'], ['highlight-countries', 'Highlight Countries Reached'], ['highlight-looplocks', 'Highlight Qualified LoopLocks'], ['highlight-impact', 'Highlight Recognized Impact']], ['Ambient equalizer', 'Wave motion', 'Soft card glow'], 'Dissolve to Programs Overview'),
  scene('09', 'Programs Overview', 'Reveal Program Tiles', [['program-campaigns', 'Highlight Campaigns'], ['program-events', 'Highlight Events'], ['program-changemakers', 'Highlight Changemakers'], ['program-stories', 'Highlight Creator Stories']], ['Equalizer pulse', 'Particle drift'], 'Dissolve to Participation Journey'),
  scene('10', 'Participation Journey', 'Reveal First Journey Step', Array.from({ length: 5 }, (_, i) => [`journey-${i + 1}`, `Advance to Journey Step ${i + 1}`]), ['Connector pulse'], 'Dissolve to EchoLoop'),
  scene('11', 'EchoLoop Explained', 'Fade In Diagram', [['term-looplink', 'Highlight LoopLink'], ['term-loopcode', 'Highlight LoopCode'], ['term-looplock', 'Highlight LoopLock'], ['term-activity', 'Highlight Loop Activity']], ['Connector glow'], 'Dissolve to Loop Activity'),
  scene('12', 'Access Levels Vertical Climb', 'Reveal Access Panel', [['level-participation', 'Highlight Participation Level'], ['level-vip', 'Highlight VIP Access'], ['level-signature', 'Highlight Signature VIP']], ['Soft card glow'], 'Dissolve to Builder Tiers'),
  scene('13', 'Community Builder Tiers', 'Reveal Tier Cards', [['tier-builder', 'Highlight Builder'], ['tier-advocate', 'Highlight Advocate'], ['tier-champion', 'Highlight Champion'], ['tier-partner', 'Highlight Partner'], ['tier-elite', 'Highlight Partner Elite']], ['Ambient glow'], 'Dissolve to Impact Statistics'),
  scene('14', 'Live Enrollment Invitation', 'Dissolve and Reveal QR', [['level-participation', 'Highlight Participation Level'], ['level-vip', 'Highlight VIP Access'], ['level-signature', 'Highlight Signature VIP'], ['builder-cta', 'Pulse Join as a Builder']], ['QR glow'], 'Exit Enrollment Scene'),
  scene('15', 'Loop Activity and Recognized Impact', 'Fade In Status Panel', [['status-pending', 'Highlight Pending LoopLock'], ['status-confirmed', 'Highlight Confirmed LoopLock'], ['status-qualified', 'Highlight Qualified LoopLock'], ['status-impact-pending', 'Highlight Impact Pending'], ['status-impact-confirmed', 'Highlight Impact Confirmed'], ['status-released', 'Highlight Impact Released']], ['Status shimmer'], 'Dissolve to Live Enrollment'),
  scene('16', 'Bema Hub Walkthrough Home Dashboard', 'Reveal Dashboard', [['dashboard-today', 'Highlight Today on Bema Hub'], ['dashboard-events', 'Highlight Upcoming Events'], ['dashboard-campaigns', 'Highlight Featured Campaigns']], ['Graph pulse', 'Cursor drift'], 'Dissolve to Campaigns'),
  scene('17', 'Campaigns Page Walkthrough', 'Reveal Campaign Cards', [['campaign-featured', 'Highlight Featured Campaign'], ['campaign-grid', 'Highlight Campaign Grid'], ['campaign-activity', 'Highlight Live Activity'], ['campaign-cta', 'Pulse Explore Campaigns']], ['Activity updates'], 'Zoom to Campaign Detail'),
  scene('18', 'Campaign Detail Page Creative Value', 'Page Light Sweep', [['detail-purpose', 'Highlight Campaign Purpose'], ['detail-assets', 'Highlight Participation Assets'], ['detail-levels', 'Highlight Access Levels'], ['detail-proof', 'Highlight Proof Updates']], ['Ambient screen motion'], 'Dissolve to Access Selection'),
  scene('19', 'Choosing Your Access Level', 'Reveal Access Cards', [['level-participation', 'Highlight Participation Level'], ['level-vip', 'Highlight VIP Access'], ['level-signature', 'Highlight Signature VIP']], ['Soft card glow'], 'Dissolve to Participation Assets'),
  scene('20', 'Participation Assets Delivered', 'Fade In Asset List', [['asset-music', 'Unlock Music Access'], ['asset-content', 'Unlock Exclusive Content'], ['asset-updates', 'Unlock Creator Updates'], ['asset-events', 'Unlock Event Access'], ['asset-community', 'Unlock Community Experience']], ['Panel glow'], 'Dissolve to LoopLink Activation'),
  scene('21', 'LoopLink and LoopCode Activation', 'Reveal LoopLink Card', [['reveal-code', 'Reveal LoopCode'], ['copy-link', 'Pulse Copy Control'], ['share-link', 'Pulse Share Control'], ['activity-update', 'Show Activity Update']], ['Activity indicator'], 'Dissolve to LoopLock Confirmation'),
  scene('22', 'LoopLock Confirmation', 'Reveal First Flow Node', Array.from({ length: 4 }, (_, i) => [`flow-${i + 1}`, `Advance to Flow Step ${i + 1}`]), ['Connector pulse'], 'Dissolve to Qualified LoopLocks'),
  scene('23', 'Qualified LoopLocks', 'Fade In Status Panel', [['status-pending', 'Highlight Pending'], ['status-confirmed', 'Highlight Confirmed'], ['status-qualified', 'Highlight Qualified'], ['status-not-qualified', 'Highlight Not Qualified']], ['Status glow'], 'Dissolve to Recognized Impact'),
  scene('24', 'Recognized Impact Explained', 'Fade In Title and Cards', [['point-value', 'Reveal Acknowledges Real Value'], ['point-qualified', 'Reveal Qualifying LoopLocks'], ['point-verified', 'Reveal Verified and Released']], ['Ambient card glow'], 'Dissolve to Trust and Transparency'),
  scene('25', 'Trust and Transparency', 'Reveal Trust Panel', [['trust-rules', 'Highlight Campaign Rules'], ['trust-windows', 'Highlight Verification Windows'], ['trust-proof', 'Highlight Creator Proof'], ['trust-status', 'Highlight Visible Status']], ['Shield glow'], 'Dissolve to Events'),
  scene('26', 'Events Page Walkthrough', 'Reveal Event Cards', [['event-featured', 'Highlight Featured Event'], ['event-upcoming', 'Highlight Upcoming Events'], ['event-categories', 'Highlight Categories']], ['Card breathing'], 'Zoom to Event Detail'),
  scene('27', 'Event Detail Page Join the Moment', 'Page Light Sweep', [['event-hero', 'Highlight Event Hero'], ['event-schedule', 'Highlight Schedule'], ['event-benefits', 'Highlight Attendee Benefits'], ['event-cta', 'Highlight Join CTA']], ['Ambient screen motion'], 'Dissolve to Changemakers'),
  scene('28', 'Changemakers Overview', 'Reveal Profile Grid', [['changemaker-1', 'Highlight Changemaker 1'], ['changemaker-2', 'Highlight Changemaker 2'], ['changemaker-3', 'Highlight Changemaker 3'], ['changemaker-4', 'Highlight Changemaker 4'], ['changemaker-5', 'Highlight Changemaker 5'], ['changemaker-6', 'Highlight Changemaker 6']], ['Impact badge motion'], 'Dissolve to Creator Stories'),
  scene('29', 'Creator Stories and Proof Updates', 'Reveal Story Cards', [['story-1', 'Highlight Next Story'], ['proof-update', 'Highlight Proof Update'], ['delivery-status', 'Highlight Delivery Status'], ['creator-spotlight', 'Highlight Creator Spotlight']], ['Progress bars', 'Badge glow'], 'Dissolve to My Impact'),
  scene('30', 'My Impact Dashboard', 'Reveal Dashboard Panels', [['metric-activity', 'Highlight Loop Activity'], ['metric-pending', 'Highlight Pending LoopLocks'], ['metric-qualified', 'Highlight Qualified LoopLocks'], ['metric-impact', 'Highlight Impact Status'], ['metric-tier', 'Highlight Builder Progress']], ['Metric card pulse'], 'Dissolve to Progress Tracker'),
  scene('31', 'Builder Progress Tracker', 'Reveal Tracker and Tier', [['advance-progress', 'Advance Progress Line'], ['current-tier', 'Highlight Current Tier'], ['next-target', 'Highlight Next Target']], ['Progress shimmer'], 'Dissolve to Community Momentum'),
  scene('32', 'Top Referrers and Community Momentum', 'Reveal Leaderboard', [['rank-1', 'Highlight Rank 1'], ['rank-2', 'Highlight Rank 2'], ['rank-3', 'Highlight Rank 3'], ['activity-update', 'Show Activity Update']], ['Momentum counters'], 'Dissolve to FAQ'),
  scene('33', 'Frequently Asked Questions', 'Expand FAQ Panel', Array.from({ length: 5 }, (_, i) => [`faq-${i + 1}`, `Highlight FAQ ${i + 1}`]), ['Panel breathing'], 'Dissolve to Final Enrollment'),
  scene('34', 'Final Enrollment Call to Action', 'Dissolve and Reveal QR', [['level-participation', 'Highlight Participation Level'], ['level-vip', 'Highlight VIP Access'], ['level-signature', 'Highlight Signature VIP'], ['join-builder', 'Highlight Join as a Builder'], ['chat-prompt', 'Highlight Live Chat']], ['QR pulse'], 'Dissolve to Thank You'),
  scene('35', 'Thank You and Next Steps', 'Reveal Next-Step Cards', [['step-email', 'Highlight Check Your Email'], ['step-chat', 'Highlight Join the Chat'], ['step-dashboard', 'Highlight Dashboard'], ['step-looplink', 'Highlight Share Your LoopLink']], ['Gentle card glow'], 'Fade to End Slate'),
  scene('36', 'Utility Live QA', 'Fade In Q&A Panel', [['question-1', 'Highlight Access Levels Question'], ['question-2', 'Highlight LoopLock Question'], ['question-3', 'Highlight Loop Activity Question'], ['question-4', 'Highlight Campaign Question']], ['Chat bubble drift'], 'Dissolve to Enrollment Progress'),
  scene('37', 'Utility Enrollment Progress Live', 'Reveal QR and Progress Cards', [['advance-counts', 'Advance Enrollment Counts'], ['advance-progress', 'Advance Progress Bar'], ['activity-update', 'Show Next Activity']], ['Live status pulse'], 'Dissolve to Closing or Hold'),
  scene('38', 'Utility Please Stand By', 'Smooth Hold Dissolve', [], ['Waveform loop', 'Particle drift', 'Status icon pulse'], 'Return to Live Segment'),
  scene('39', 'Utility Close Loop', 'Fade In End Screen', [['dashboard-cta', 'Highlight Dashboard'], ['looplink-cta', 'Highlight LoopLink'], ['community-cta', 'Highlight Community Chat']], ['QR glow', 'Card breathing', 'Waveform loop'], 'Fade to Black'),
]

export const sceneControlById = Object.freeze(Object.fromEntries(sceneControls.map((item) => [item.scene, item])))
